source "https://rubygems.org"

gem 'maestro_plugin', '>= 0.0.14'

#dependencies
gem 'emoji', "0.1"

group :development do
  gem 'maestro-plugin-rake-tasks'
  gem 'rake', '>=0.9.2.2'
end

group :test do
  gem 'rspec'
end
