source :rubygems

gem 'bundler', '>= 1.0.21'
gem 'rake'
gem 'zippy'

gem 'maestro_agent', '>= 1.2.0'

#dependencies
gem "emoji", "0.1"

group :test do
  gem "mocha", "0.10.0"
  gem 'rspec'
  gem 'rspec-core'
  gem 'rcov', '0.9.11'
  gem 'mocha', '0.10.0'
end
