require 'rake/clean'
require 'rspec/core/rake_task'
require 'zippy'
require 'nokogiri'
require 'json'

$:.push File.expand_path("../src", __FILE__)

CLEAN.include("manifest.json", "*-plugin-*.zip", "vendor", "package", "tmp", ".bundle")

task :default => :all
task :all => [:clean, :bundle, :spec, :package]

desc "Run specs"
RSpec::Core::RakeTask.new

desc "Get dependencies with Bundler"
task :bundle do
  sh %{bundle package}
end

def add_file( zippyfile, dst_dir, f )
  puts "Writing #{f} at #{dst_dir}"
  zippyfile["#{dst_dir}/#{f}"] = File.open(f)
end

def add_dir( zippyfile, dst_dir, d )
  glob = "#{d}/**/*"
  FileList.new( glob ).each { |f|
    if (File.file?(f))
      add_file zippyfile, dst_dir, f
    end
  }
end

desc "Package plugin zip"
task :package do
  doc = Nokogiri::XML(IO.read("pom.xml"))
  artifactId = doc.css('artifactId').first.text
  version = doc.css('version').first.text
  zip_file = "#{artifactId}-#{version}.zip"

  # update manifest
  manifest = JSON.parse(IO.read("manifest.template.json"))
  tasks =  manifest['tasks'] || manifest
  tasks.each { |t| t['version'] = version }
  File.open("manifest.json",'w'){ |f| f.write(JSON.pretty_generate(manifest)) }

  Zippy.create zip_file do |z|
    add_dir z, '.', 'src'
    add_dir z, '.', 'vendor'
    add_dir z, '.', 'images'
    add_file z, '.', 'manifest.json'
    add_file z, '.', 'README.md'
    add_file z, '.', 'LICENSE'
  end
end
